### ISSUE TITLE
Missing Warlords Class Leaderboards

### ISSUE THREAD

**Issue by Poshio12** [Plancke/PlanckeBugs#4]
Mage Class leaderboard (warlords) displays 57 players. 
Warrior leaderboard shows 462 players
Paladin board shows none.
Shaman board shows 6 players.

The numbers change every few hours, but the problem has lasted for at least two days.

**Comment by Plancke** [comment]
I have no clue how that is happening tbh, i'll look into it later. Quite busy right now

**Comment by Plancke** [comment]
fixed
